import { Epilogue } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';


const epilogue = Epilogue({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-epilogue',
});

// Configure the local font
const clashDisplay = localFont({
  src: '../assets/fonts/ClashDisplay.ttf', // path relative to this file
  variable: '--font-clash-display',        // the CSS variable name
  display: 'swap',
});

export const metadata = {
  title: "QuickHire",
  // description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${epilogue.variable} ${clashDisplay.variable}`}>
      <body>{children}</body>
    </html >
  );
}